### ISSUE TITLE
How to pass password to rsmq-cli?

### ISSUE THREAD

**Issue by 5amfung** [mpneuried/rsmq-cli#4]
I don't seem to find `-a` or something that would allow me to pass the password.

**Comment by mpneuried** [comment]
i added a new configuration `--clientopt` to define the node-redis connection options.
It's also possible to define the options as defaults via `rsmq config set clientopt.password supersecret`.

Hope this helps!

**Comment by 5amfung** [comment]
Works as expected.

```
rsmq ls --clientopt url='<ADD YOUR REDIS_URL HERE>'
```
